[connections.snowflake]
account = "lx83481.eu-west-2.aws.snowflakecomputing.com"
user = "AMLODZIKBADGES3"
password = "Snow12345"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
